# Site
favicon: images/favicon.ico

# Personal info
name: Business Portrait
title: More than a headshot
email: tommi@saltiolaexperience.com

# Social links
# dribbble_username: jekyll
# facebook_username: jekyll
instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Business Portrait is more than a headshot. Every detail of the shot is a decicion to make you stand out for your audience

# Projects Section
# projects_title: Projects
<div data-prodibi='{"type":"grid","settings":{"container":"wy2kyl28z89gm6v","account":"saltiola7"}}'><script>;!function() {if (window.prodibiAsync == null) { var s = document.createElement('script'); s.async = !0; s.src = 'https://max1.prodibicdn.com/libraries/pages/prodibi.embed.2.0.min.js'; document.body.appendChild(s); }window.prodibiAsync = window.prodibiAsync || [];prodibiAsync.push({ type: "settings", settings: { account: "saltiola7" } });}();</script></div>

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
