# Site
favicon: images/favicon.ico

# Personal info
name: Business Portrait
title: More than a headshot
email: tommi@saltiolaexperience.com

# Social links
# dribbble_username: jekyll
# facebook_username: jekyll
instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Business Portrait is more than a headshot. Every detail of the shot is a decicion to make you stand out for your audience

# Projects Section
# projects_title: Projects

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag